/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Main.*;
import com.chillyfacts.com.QR_Generate;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author iodin
 */
public class Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    Connection cConexion;  // La conexión
    java.sql.Statement st;
    
    
    void cargar(){
        coddptotxt.setText(Main.cod);nocontroltxt.setText(Main.nocontrol);nombretxt.setText(Main.nombre);
        nombre=nocontrol=apa=ama=semestre=cod="";
    }
    
    void closeConexion(){
        try {
            cConexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Proveedor() {
        try {
            Class.forName("org.postgresql.Driver");
            
            cConexion = Login.getcConexion();
        } catch (Exception e) {

        }
        initComponents();
        this.setLocationRelativeTo(null);
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelNocontrol = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelSemestre = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        coddptotxt = new javax.swing.JTextField();
        nocontroltxt = new javax.swing.JTextField();
        jButtonGenerarQR = new javax.swing.JButton();
        jLabelQR = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtonSalir.setBorder(null);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 70, 20));

        jLabelTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabelTitle.setText("FORMULARIO - PROVEEDOR");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelNocontrol.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNocontrol.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNocontrol.setText("NO. CONTROL :");
        getContentPane().add(jLabelNocontrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombre.setText("NOMBRE :");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabelSemestre.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelSemestre.setForeground(new java.awt.Color(51, 51, 51));
        jLabelSemestre.setText("CODDPTO");
        getContentPane().add(jLabelSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        nombretxt.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 330, -1));

        coddptotxt.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(coddptotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 330, -1));

        nocontroltxt.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(nocontroltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 330, -1));

        jButtonGenerarQR.setBackground(new java.awt.Color(153, 255, 153));
        jButtonGenerarQR.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonGenerarQR.setText("GENERAR");
        jButtonGenerarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarQRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        jLabelQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SIAPrueba1.png"))); // NOI18N
        getContentPane().add(jLabelQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jButtonGuardar.setBackground(new java.awt.Color(153, 255, 153));
        jButtonGuardar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        jButtondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete Icon.png"))); // NOI18N
        jButtondelete.setContentAreaFilled(false);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtondelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 70, 70));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SIA fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        new Main().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGenerarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarQRActionPerformed
        QR_Generate g = new QR_Generate();
        g.setNo_control(nocontroltxt.getText());
        g.generate();
    }//GEN-LAST:event_jButtonGenerarQRActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        new Main().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
                            String sql="select agregarProveedor('"+nocontroltxt.getText()+"','"+nombretxt.getText()+"','"+coddptotxt.getText()+"')";
        try {
            st = cConexion.createStatement();
            st.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        String sql = "delete from proveedor where no_control = '"+nocontroltxt.getText()+"'";
        try {
            st = cConexion.createStatement();
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Proveedor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coddptotxt;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGenerarQR;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNocontrol;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelQR;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField nocontroltxt;
    private javax.swing.JTextField nombretxt;
    // End of variables declaration//GEN-END:variables
}
